/* 
 * This file was generated by running
 *   $ pfsc license about ise
 * in the pfsc-manage project.
 */
export const softwareTableRows = `


<!-- pfsc-ise -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/pfsc-ise/tree/v23.1">
pfsc-ise
</a><span class="vers" data-proj-name="pfsc-ise">
23.1
</span></td>
<td><a target="_blank"
href="https://github.com/proofscape/pfsc-ise/blob/v23.1/LICENSE">
Apache-2.0
</a></td></tr>

<!-- elkjs -->
<tr><td><a target="_blank"
href="https://github.com/kieler/elkjs">
elkjs
</a><span class="vers" data-proj-name="elkjs">
0.8.1
</span></td>
<td><a target="_blank"
href="https://github.com/kieler/elkjs/blob/master/LICENSE.md">
EPL-2.0
</a></td></tr>

<!-- sympy -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/sympy">
sympy
</a><span class="vers" data-proj-name="sympy">
(DisplayLang fork v0.10.4)
</span></td>
<td><a target="_blank"
href="https://github.com/sympy/sympy/blob/master/LICENSE">
BSD
</a></td></tr>

<!-- pdf.js -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/pfsc-pdf">
pdf.js
</a><span class="vers" data-proj-name="pdf.js">
(Proofscape fork v2.1.1)
</span></td>
<td><a target="_blank"
href="https://www.apache.org/licenses/LICENSE-2.0.txt">
Apache 2.0
</a></td></tr>

<!-- pyodide -->
<tr><td><a target="_blank"
href="https://github.com/pyodide/pyodide/tree/0.19.1">
pyodide
</a><span class="vers" data-proj-name="pyodide">
0.19.1
</span></td>
<td><a target="_blank"
href="https://github.com/pyodide/pyodide/blob/0.19.1/LICENSE">
MPL-2.0
</a></td></tr>

<!-- pfsc-examp -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/pfsc-examp/tree/v0.22.8">
pfsc-examp
</a><span class="vers" data-proj-name="pfsc-examp">
0.22.8
</span></td>
<td><a target="_blank"
href="https://www.apache.org/licenses/LICENSE-2.0.txt">
Apache 2.0
</a></td></tr>

<!-- displaylang -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/displaylang">
displaylang
</a><span class="vers" data-proj-name="displaylang">
0.22.8
</span></td>
<td><a target="_blank"
href="https://www.apache.org/licenses/LICENSE-2.0.txt">
Apache 2.0
</a></td></tr>

<!-- lark-parser -->
<tr><td><a target="_blank"
href="https://github.com/lark-parser/lark/tree/0.6.7">
lark-parser
</a><span class="vers" data-proj-name="lark-parser">
0.6.7
</span></td>
<td><a target="_blank"
href="https://github.com/lark-parser/lark/blob/0.6.7/LICENSE">
MIT
</a></td></tr>

<!-- typeguard -->
<tr><td><a target="_blank"
href="https://github.com/agronholm/typeguard/tree/2.13.3">
typeguard
</a><span class="vers" data-proj-name="typeguard">
2.13.3
</span></td>
<td><a target="_blank"
href="https://github.com/agronholm/typeguard/blob/2.13.3/LICENSE">
MIT
</a></td></tr>

<!-- pfsc-util -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/pfsc-util/tree/v0.22.8">
pfsc-util
</a><span class="vers" data-proj-name="pfsc-util">
0.22.8
</span></td>
<td><a target="_blank"
href="https://www.apache.org/licenses/LICENSE-2.0.txt">
Apache 2.0
</a></td></tr>

<!-- mpmath -->
<tr><td><a target="_blank"
href="https://github.com/fredrik-johansson/mpmath/tree/1.2.1">
mpmath
</a><span class="vers" data-proj-name="mpmath">
1.2.1
</span></td>
<td><a target="_blank"
href="https://github.com/fredrik-johansson/mpmath/blob/1.2.1/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- Jinja2 -->
<tr><td><a target="_blank"
href="https://github.com/pallets/jinja//tree/3.0.3">
Jinja2
</a><span class="vers" data-proj-name="Jinja2">
3.0.3
</span></td>
<td><a target="_blank"
href="https://github.com/pallets/jinja/blob/3.0.3/LICENSE.rst">
BSD-3-Clause
</a></td></tr>

<!-- MarkupSafe -->
<tr><td><a target="_blank"
href="https://github.com/pallets/markupsafe/tree/2.0.1">
MarkupSafe
</a><span class="vers" data-proj-name="MarkupSafe">
2.0.1
</span></td>
<td><a target="_blank"
href="https://github.com/pallets/markupsafe/blob/2.0.1/LICENSE.rst">
BSD-3-Clause
</a></td></tr>

<!-- ace-builds -->
<tr><td><a target="_blank"
href="https://github.com/ajaxorg/ace-builds/tree/v1.4.8">
ace-builds
</a><span class="vers" data-proj-name="ace-builds">
1.4.8
</span></td>
<td><a target="_blank"
href="https://github.com/ajaxorg/ace-builds/blob/v1.4.8/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- browser-peers -->
<tr><td><a target="_blank"
href="https://github.com/skieffer/browser-peers/tree/v0.2.0">
browser-peers
</a><span class="vers" data-proj-name="browser-peers">
0.2.0
</span></td>
<td><a target="_blank"
href="https://github.com/skieffer/browser-peers/blob/v0.2.0/LICENSE">
MIT
</a></td></tr>

<!-- dijit -->
<tr><td><a target="_blank"
href="https://github.com/dojo/dijit/tree/1.16.4">
dijit
</a><span class="vers" data-proj-name="dijit">
1.16.4
</span></td>
<td><a target="_blank"
href="https://github.com/dojo/dijit/blob/1.16.4/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- dojo-util -->
<tr><td><a target="_blank"
href="https://github.com/dojo/util/tree/1.16.2">
dojo-util
</a><span class="vers" data-proj-name="dojo-util">
1.16.2
</span></td>
<td><a target="_blank"
href="https://github.com/dojo/util/blob/1.16.2/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- dojox -->
<tr><td><a target="_blank"
href="https://github.com/dojo/dojox/tree/1.16.4">
dojox
</a><span class="vers" data-proj-name="dojox">
1.16.4
</span></td>
<td><a target="_blank"
href="https://github.com/dojo/dojox/blob/1.16.4/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- dragula -->
<tr><td><a target="_blank"
href="https://github.com/bevacqua/dragula/tree/v3.7.3">
dragula
</a><span class="vers" data-proj-name="dragula">
3.7.3
</span></td>
<td><a target="_blank"
href="https://github.com/bevacqua/dragula/blob/v3.7.3/license">
MIT
</a></td></tr>

<!-- lru-cache -->
<tr><td><a target="_blank"
href="https://github.com/isaacs/node-lru-cache/tree/v6.0.0">
lru-cache
</a><span class="vers" data-proj-name="lru-cache">
6.0.0
</span></td>
<td><a target="_blank"
href="https://github.com/isaacs/node-lru-cache/blob/v6.0.0/LICENSE">
ISC
</a></td></tr>

<!-- mathjax -->
<tr><td><a target="_blank"
href="https://github.com/mathjax/MathJax/tree/3.0.1">
mathjax
</a><span class="vers" data-proj-name="mathjax">
3.0.1
</span></td>
<td><a target="_blank"
href="https://github.com/mathjax/MathJax/blob/3.0.1/LICENSE">
Apache-2.0
</a></td></tr>

<!-- nanobar -->
<tr><td><a target="_blank"
href="https://github.com/jacoborus/nanobar/tree/v0.4.2">
nanobar
</a><span class="vers" data-proj-name="nanobar">
0.4.2
</span></td>
<td><a target="_blank"
href="https://github.com/jacoborus/nanobar/blob/v0.4.2/LICENSE">
MIT
</a></td></tr>

<!-- pfsc-moose -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/pfsc-moose/tree/v0.22.8">
pfsc-moose
</a><span class="vers" data-proj-name="pfsc-moose">
0.22.8
</span></td>
<td><a target="_blank"
href="https://github.com/proofscape/pfsc-moose/blob/v0.22.8/LICENSE">
Apache-2.0
</a></td></tr>

<!-- socket.io-client -->
<tr><td><a target="_blank"
href="https://github.com/socketio/socket.io-client/tree/4.4.1">
socket.io-client
</a><span class="vers" data-proj-name="socket.io-client">
4.4.1
</span></td>
<td><a target="_blank"
href="https://github.com/socketio/socket.io-client/blob/4.4.1/LICENSE">
MIT
</a></td></tr>

<!-- uuid -->
<tr><td><a target="_blank"
href="https://github.com/uuidjs/uuid/tree/v8.3.2">
uuid
</a><span class="vers" data-proj-name="uuid">
8.3.2
</span></td>
<td><a target="_blank"
href="https://github.com/uuidjs/uuid/blob/v8.3.2/LICENSE.md">
MIT
</a></td></tr>

<!-- webextension-polyfill -->
<tr><td><a target="_blank"
href="https://github.com/mozilla/webextension-polyfill/tree/0.6.0">
webextension-polyfill
</a><span class="vers" data-proj-name="webextension-polyfill">
0.6.0
</span></td>
<td><a target="_blank"
href="https://github.com/mozilla/webextension-polyfill/blob/0.6.0/LICENSE">
MPL-2.0
</a></td></tr>

<!-- dojo -->
<tr><td><a target="_blank"
href="https://github.com/dojo/dojo/tree/1.16.4">
dojo
</a><span class="vers" data-proj-name="dojo">
1.16.4
</span></td>
<td><a target="_blank"
href="https://github.com/dojo/dojo/blob/1.16.4/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- contra -->
<tr><td><a target="_blank"
href="https://github.com/bevacqua/contra/tree/v1.9.4">
contra
</a><span class="vers" data-proj-name="contra">
1.9.4
</span></td>
<td><a target="_blank"
href="https://github.com/bevacqua/contra/blob/v1.9.4/LICENSE">
MIT
</a></td></tr>

<!-- crossvent -->
<tr><td><a target="_blank"
href="https://github.com/bevacqua/crossvent/tree/v1.5.5">
crossvent
</a><span class="vers" data-proj-name="crossvent">
1.5.5
</span></td>
<td><a target="_blank"
href="https://github.com/bevacqua/crossvent/blob/v1.5.5/LICENSE">
MIT
</a></td></tr>

<!-- yallist -->
<tr><td><a target="_blank"
href="https://github.com/isaacs/yallist/tree/v4.0.0">
yallist
</a><span class="vers" data-proj-name="yallist">
4.0.0
</span></td>
<td><a target="_blank"
href="https://github.com/isaacs/yallist/blob/v4.0.0/LICENSE">
ISC
</a></td></tr>

<!-- d3-ease -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-ease/tree/v1.0.7">
d3-ease
</a><span class="vers" data-proj-name="d3-ease">
1.0.7
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-ease/blob/v1.0.7/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- d3-selection -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-selection/tree/v1.4.2">
d3-selection
</a><span class="vers" data-proj-name="d3-selection">
1.4.2
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-selection/blob/v1.4.2/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- d3-transition -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-transition/tree/v1.3.2">
d3-transition
</a><span class="vers" data-proj-name="d3-transition">
1.3.2
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-transition/blob/v1.3.2/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- webcola -->
<tr><td><a target="_blank"
href="https://github.com/tgdwyer/WebCola">
webcola
</a><span class="vers" data-proj-name="webcola">
3.4.0
</span></td>
<td><a target="_blank"
href="https://github.com/tgdwyer/WebCola/blob/master/LICENSE">
MIT
</a></td></tr>

<!-- @socket.io/component-emitter -->
<tr><td><a target="_blank"
href="https://github.com/socketio/emitter/tree/3.0.0">
@socket.io/component-emitter
</a><span class="vers" data-proj-name="@socket.io/component-emitter">
3.0.0
</span></td>
<td><a target="_blank"
href="https://github.com/socketio/emitter/blob/3.0.0/LICENSE">
MIT
</a></td></tr>

<!-- backo2 -->
<tr><td><a target="_blank"
href="https://github.com/mokesmokes/backo">
backo2
</a><span class="vers" data-proj-name="backo2">
1.0.2
</span></td>
<td><a target="_blank"
href="https://github.com/mokesmokes/backo/blob/280597dede9a7c97ff47a3fa01f3b412c1d94438/LICENSE">
MIT
</a></td></tr>

<!-- debug -->
<tr><td><a target="_blank"
href="https://github.com/debug-js/debug/tree/4.3.3">
debug
</a><span class="vers" data-proj-name="debug">
4.3.3
</span></td>
<td><a target="_blank"
href="https://github.com/debug-js/debug/blob/4.3.3/LICENSE">
MIT
</a></td></tr>

<!-- engine.io-client -->
<tr><td><a target="_blank"
href="https://github.com/socketio/engine.io-client/tree/6.1.1">
engine.io-client
</a><span class="vers" data-proj-name="engine.io-client">
6.1.1
</span></td>
<td><a target="_blank"
href="https://github.com/socketio/engine.io-client/blob/6.1.1/LICENSE">
MIT
</a></td></tr>

<!-- parseuri -->
<tr><td><a target="_blank"
href="https://github.com/get/parseuri/tree/v0.0.6">
parseuri
</a><span class="vers" data-proj-name="parseuri">
0.0.6
</span></td>
<td><a target="_blank"
href="https://github.com/get/parseuri/blob/v0.0.6/LICENSE">
MIT
</a></td></tr>

<!-- socket.io-parser -->
<tr><td><a target="_blank"
href="https://github.com/socketio/socket.io-parser/tree/4.1.1">
socket.io-parser
</a><span class="vers" data-proj-name="socket.io-parser">
4.1.1
</span></td>
<td><a target="_blank"
href="https://github.com/socketio/socket.io-parser/blob/4.1.1/LICENSE">
MIT
</a></td></tr>

<!-- atoa -->
<tr><td><a target="_blank"
href="https://github.com/bevacqua/atoa">
atoa
</a><span class="vers" data-proj-name="atoa">
1.0.0
</span></td>
<td><a target="_blank"
href="https://github.com/bevacqua/atoa/blob/master/license">
MIT
</a></td></tr>

<!-- ticky -->
<tr><td><a target="_blank"
href="https://github.com/bevacqua/ticky/tree/v1.0.1">
ticky
</a><span class="vers" data-proj-name="ticky">
1.0.1
</span></td>
<td><a target="_blank"
href="https://github.com/bevacqua/ticky/blob/v1.0.1/license">
MIT
</a></td></tr>

<!-- custom-event -->
<tr><td><a target="_blank"
href="https://github.com/webmodules/custom-event/tree/1.0.1">
custom-event
</a><span class="vers" data-proj-name="custom-event">
1.0.1
</span></td>
<td><a target="_blank"
href="https://github.com/webmodules/custom-event/blob/725c41146f970df345d57cd97b2bf5acd6c8e9f7/LICENSE">
MIT
</a></td></tr>

<!-- d3-color -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-color/tree/v1.4.1">
d3-color
</a><span class="vers" data-proj-name="d3-color">
1.4.1
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-color/blob/v1.4.1/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- d3-dispatch -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-dispatch/tree/v1.0.6">
d3-dispatch
</a><span class="vers" data-proj-name="d3-dispatch">
1.0.6
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-dispatch/blob/v1.0.6/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- d3-interpolate -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-interpolate/tree/v1.4.0">
d3-interpolate
</a><span class="vers" data-proj-name="d3-interpolate">
1.4.0
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-interpolate/blob/v1.4.0/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- d3-timer -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-timer/tree/v1.0.10">
d3-timer
</a><span class="vers" data-proj-name="d3-timer">
1.0.10
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-timer/blob/v1.0.10/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- d3-drag -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-drag/tree/v1.2.5">
d3-drag
</a><span class="vers" data-proj-name="d3-drag">
1.2.5
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-drag/blob/v1.2.5/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- d3-shape -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-shape/tree/v1.3.7">
d3-shape
</a><span class="vers" data-proj-name="d3-shape">
1.3.7
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-shape/blob/v1.3.7/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- ms -->
<tr><td><a target="_blank"
href="https://github.com/vercel/ms/tree/2.1.2">
ms
</a><span class="vers" data-proj-name="ms">
2.1.2
</span></td>
<td><a target="_blank"
href="https://github.com/vercel/ms/blob/2.1.2/license.md">
MIT
</a></td></tr>

<!-- engine.io-parser -->
<tr><td><a target="_blank"
href="https://github.com/socketio/engine.io-parser/tree/5.0.3">
engine.io-parser
</a><span class="vers" data-proj-name="engine.io-parser">
5.0.3
</span></td>
<td><a target="_blank"
href="https://github.com/socketio/engine.io-parser/blob/5.0.3/LICENSE">
MIT
</a></td></tr>

<!-- has-cors -->
<tr><td><a target="_blank"
href="https://github.com/component/has-cors/tree/1.1.0">
has-cors
</a><span class="vers" data-proj-name="has-cors">
1.1.0
</span></td>
<td><a target="_blank"
href="https://github.com/component/has-cors/blob/27e9b96726b669e9594350585cc1e97474d3f995/Readme.md">
MIT
</a></td></tr>

<!-- parseqs -->
<tr><td><a target="_blank"
href="https://github.com/get/querystring/tree/v0.0.6">
parseqs
</a><span class="vers" data-proj-name="parseqs">
0.0.6
</span></td>
<td><a target="_blank"
href="https://github.com/get/querystring/blob/v0.0.6/LICENSE">
MIT
</a></td></tr>

<!-- ws -->
<tr><td><a target="_blank"
href="https://github.com/websockets/ws/tree/8.2.3">
ws
</a><span class="vers" data-proj-name="ws">
8.2.3
</span></td>
<td><a target="_blank"
href="https://github.com/websockets/ws/blob/8.2.3/LICENSE">
MIT
</a></td></tr>

<!-- xmlhttprequest-ssl -->
<tr><td><a target="_blank"
href="https://github.com/mjwwit/node-XMLHttpRequest/tree/2.0.0">
xmlhttprequest-ssl
</a><span class="vers" data-proj-name="xmlhttprequest-ssl">
2.0.0
</span></td>
<td><a target="_blank"
href="https://github.com/mjwwit/node-XMLHttpRequest/blob/2.0.0/LICENSE">
MIT
</a></td></tr>

<!-- yeast -->
<tr><td><a target="_blank"
href="https://github.com/unshiftio/yeast/tree/0.1.2">
yeast
</a><span class="vers" data-proj-name="yeast">
0.1.2
</span></td>
<td><a target="_blank"
href="https://github.com/unshiftio/yeast/blob/0.1.2/LICENSE">
MIT
</a></td></tr>

<!-- d3-path -->
<tr><td><a target="_blank"
href="https://github.com/d3/d3-path/tree/v1.0.9">
d3-path
</a><span class="vers" data-proj-name="d3-path">
1.0.9
</span></td>
<td><a target="_blank"
href="https://github.com/d3/d3-path/blob/v1.0.9/LICENSE">
BSD-3-Clause
</a></td></tr>

<!-- @socket.io/base64-arraybuffer -->
<tr><td><a target="_blank"
href="https://github.com/socketio/base64-arraybuffer/tree/v1.0.2">
@socket.io/base64-arraybuffer
</a><span class="vers" data-proj-name="@socket.io/base64-arraybuffer">
1.0.2
</span></td>
<td><a target="_blank"
href="https://github.com/socketio/base64-arraybuffer/blob/v1.0.2/LICENSE">
MIT
</a></td></tr>
`;